Non/feat/session history
2110336-SoftwareEngineering2-2021-2/sec2_ChocoTech pull request #85
Opened 2022-03-25 15:16 UTC by Uttanon

2022-03-25 16:30 UTC, saenyakorn requested changes
เอ๊ะ เดี๋ยวทำไมมี component ซ้ำกัน 2 ที่ ใน lib/mui กับ frontend

2022-03-25 16:30 UTC, saenyakorn commented on apps/doji-frontend/src/components/Card/SessionHistoryCancelButton.tsx
> +        <Box sx={style}>
ใช้ `styled` แทน

2022-03-25 16:30 UTC, saenyakorn commented on apps/doji-frontend/src/components/Card/SessionHistoryCancelButton.tsx
> +      <Modal
ใช้ Dialog แทน Modal มันไม่มี animation

2022-03-25 16:30 UTC, saenyakorn commented on apps/doji-frontend/src/components/Card/SessionHistoryCancelButton.tsx
> +              <Button variant="text" onClick={() => handleClose()}>
```suggestion
              <Button variant="text" onClick={handleClose}>
```

2022-03-25 16:30 UTC, saenyakorn commented on apps/doji-frontend/src/components/Card/SessionHistoryCard.tsx
> +  }
ติด `//TODO` ไว้

2022-03-26 00:35 UTC, Uttanon commented on apps/doji-frontend/src/components/Card/SessionHistoryCancelButton.tsx
> +            <Box display="flex" flexDirection="column" alignItems="center" gap="8px">
Box ใน แบ่งระหว่างชื่อกับ วันที่
Box นอกแบ่งระหว่าง ก้อนของชื่อกับวันที่ กับ ปุ่ม
เปลี่ยน Box เป็น Stack แล้ว

2022-03-26 00:37 UTC, Uttanon commented on apps/doji-frontend/src/components/Card/SessionHistoryCancelButton.tsx
> +  const CreateToast = () =>
แก้เรียบร้อย

2022-03-26 00:47 UTC, Uttanon commented on apps/doji-frontend/src/components/Card/SessionHistoryCancelButton.tsx
> +        <Box sx={style}>
แก้แล้ว

2022-03-26 00:49 UTC, Uttanon commented on apps/doji-frontend/src/components/Card/SessionHistoryCancelButton.tsx
> +      <Modal
ใช้ Dialog แล้วทำให้ Modal บัค

2022-03-26 01:01 UTC, merged